// <copyright file="CompanyInfo.cs" company="Gavin Greig">
// Copyright (c) Dr. Gavin T.D. Greig, 2020.
// </copyright>

#if Razor
// <auto-generated/>
// Because of the way Razor compilation works we need to force StyleCop to ignore
// this file during Razor compilation.
#endif

#if JavaScript
#else
[assembly: System.Security.SecurityRules(System.Security.SecurityRuleSet.Level2)]
#endif

// General Information about an assembly is controlled through the following
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
/*
[assembly: System.Reflection.AssemblyCompany("Gavin Greig")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Dr. Gavin T.D. Greig. 2020")]
*/
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyCulture("")] // Empty string for any main (non-satellite) assembly

#if JavaScript
#else
// Setting ComVisible to false makes the types in this assembly not visible
// to COM components.  If you need to access a type in this assembly from
// COM, set the ComVisible attribute to true on that type.
[assembly: System.Runtime.InteropServices.ComVisible(false)]

#endif

#if NETCOREAPP || JavaScript
[assembly: System.CLSCompliant(false)]
#else
[assembly: System.CLSCompliant(true)]
#endif