// <copyright file="ProductInfo.cs" company="Gavin Greig">
// Copyright (c) Dr. Gavin T.D. Greig, 2020.
// </copyright>

#if Razor
// <auto-generated/>
// Because of the way Razor compilation works we need to force StyleCop to ignore
// this file during Razor compilation.
#endif

using System.Reflection;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyProduct("")]
//[assembly: AssemblyDescription("Built from changeset ")]

// The following version attributes are placeholders. Do not remove.
// On the build server, valid values should be automatically injected in their place (not yet in place).
[assembly: AssemblyVersion("0.1.1.1")]
[assembly: AssemblyFileVersion("0.1.1.1")]
[assembly: AssemblyInformationalVersion("0.1.1.1")]