# Intended to run for every commit; should build, run quick quality checks and unit tests.
# Swift feedback is expected.

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#jobs:
#- job: build
#  displayName: "Project Build"
  
trigger:
- master

pool:
  vmImage:  'ubuntu-latest'

steps:
- task: NuGetAuthenticate@0
  inputs:
    nuGetServiceConnections: 

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'

# Begin testing:
# https://stackoverflow.com/a/61481951
- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    arguments: '--collect:"XPlat Code Coverage" -- RunConfiguration.DisableAppDomain=true'
    testRunTitle: 'Run Test and collect Coverage'

- task: DotNetCoreCLI@2
  displayName: 'New Manifest'
  inputs:
    command: 'custom'
    custom: 'new'
    arguments: 'tool-manifest --force'

- task: DotNetCoreCLI@2
  displayName: 'Install ReportGenerator'
  inputs:
    command: custom
    custom: tool
    arguments: install dotnet-reportgenerator-globaltool

- task: DotNetCoreCLI@2
  displayName: 'Collate Code Coverage Results'
  inputs:
    command: custom
    custom: tool
    arguments: 'run reportgenerator -reports:$(Agent.TempDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/coverlet/reports -reporttypes:"Cobertura"'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish Code Coverage Results'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: $(Build.SourcesDirectory)/coverlet/reports/Cobertura.xml  

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
